### ISSUE TITLE
Internal Server Error on PUT with JSON value

### ISSUE THREAD

**Issue by peterhellberg** [bluzi/jsonstore#14]
```
curl -X PUT -H 'Content-Type: application/json' -d '12345' https://www.jsonstore.io/1ba7860f742fc15d5b6e1508e2de1e0cde2c396f7c52a877905befb4e970eaaf/a-number
```

```
curl -X PUT -H 'Content-Type: application/json' -d 'true' https://www.jsonstore.io/1ba7860f742fc15d5b6e1508e2de1e0cde2c396f7c52a877905befb4e970eaaf/a-boolean
```

#### Both requests result in a 500:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```

### Using a JSON object work just fine:

```
curl -X PUT -H 'Content-Type: application/json' -d '{"b":true, "n":12345}' https://www.jsonstore.io/1ba7860f742fc15d5b6e1508e2de1e0cde2c396f7c52a877905befb4e970eaaf/an-object
```

```
{"result":true}
```

**Comment by KeizerDev** [comment]
This isn't really a bug maybe the server should give a different error code back but what do you expect else? You are setting the `Content-Type` to `application/json` and you do give a invalid JSON data object.

**Comment by peterhellberg** [comment]
It is valid JSON, just not an object.

**Comment by peterhellberg** [comment]
And support for JSON values would make it more convenient to change a single value with a PUT request. Otherwise you would have to PUT an object to the parent element with a key for the given value.

**Comment by KeizerDev** [comment]
My bad, I'm sorry

**Comment by peterhellberg** [comment]
### All JSON value types:

![value](http://json.org/value.gif)

**Comment by akshendra** [comment]
@peterhellberg this issue should be fixed in https://github.com/bluzi/jsonstore/pull/12. `body-parser` was in strict mode, with takes only array and object json values.

**Comment by peterhellberg** [comment]
@akshendra Ok, good. (Please correct the spelling in the error message)

**Comment by bluzi** [comment]
@peterhellberg Can you verify it's solved?

**Comment by peterhellberg** [comment]
@bluzi The two failing requests in this issue is still failing with an Internal Server Error.

**Comment by peterhellberg** [comment]
**PUT** with a JSON object against the parent object work though. It would just be more convenient to be able to PUT a JSON value directly.

```
curl -X PUT -H 'Content-Type: application/json' -d '{"b":false}' https://www.jsonstore.io/1ba7860f742fc15d5b6e1508e2de1e0cde2c396f7c52a877905befb4e970eaaf/an-object
```
